name: Publish Package

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Atualizado para usar Node.js 20

      - name: Setup Node.js
        uses: actions/setup-node@v4 # Atualizado para usar Node.js 20
        with:
          node-version: "20" # Utilizando a versão mais recente do Node.js
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build package
        run: npm run build # Certifique-se de que tem um script "build" no package.json

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
